language: ruby
rvm:
  - 2.3.3
before_install:
  - openssl aes-256-cbc -K $encrypted_ecabfac08d8e_key -iv $encrypted_ecabfac08d8e_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host mritd.me\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - bundle install
  - bundle exec jekyll build
after_success:
  - git clone https://github.com/zhouchangxun/blog.git
  - cd mritd.me && rm -rf * && cp -r ../_site/* .
  - git config user.name "zhouchangxun"
  - git config user.email "changxunzhou@qq.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force https://$DEPLOY_TOKEN@github.com/zhouchangxun/blog.git master
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
