language: ruby
rvm:
  - 2.3.3
before_install:
  - echo "zcx:before_install..."
  - gem install jekyll -v '2.0.0.alpha.1'
script:
  - jekyll build
after_success:
  - git clone https://github.com/zhouchangxun/blog.git
  - cd mritd.me && rm -rf * && cp -r ../_site/* .
  - git config user.name "zhouchangxun"
  - git config user.email "changxunzhou@qq.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force https://$DEPLOY_TOKEN@github.com/zhouchangxun/blog.git master
  - echo "zcx:after_success..."
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
