language: ruby
rvm:
  - 2.3.3
before_install:
  - echo "zcx:before_install..."
script:
  - bundle install
  - bundle exec jekyll build
after_success:
  - ls -R
  - git clone https://github.com/zhouchangxun/blog.git
  - cd blog && rm -rf * && cp -r ../_site/* .
  - git config user.name "zhouchangxun"
  - git config user.email "changxunzhou@qq.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force https://$DEPLOY_TOKEN@github.com/zhouchangxun/blog.git master
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
